### ISSUE TITLE
Pick a flashier theme

### ISSUE THREAD

**Issue by PraveshMoelchand** [emieldesmidt/trustchain-superapp#21]
The suggestion to pick a different, flashier theme was proposed. More info about Android themes can be found [here](https://developer.android.com/guide/topics/ui/look-and-feel/themes)

**Comment by emieldesmidt** [comment]
Really not a fan of this one, am quite content with the current looks

**Comment by PraveshMoelchand** [comment]
Yeah, current theme is fine, but I am open for a fresh new look. It shouldn't take up too much time though, hence the `prio::low` label.

**Comment by PraveshMoelchand** [comment]
Not deemed necessary
