### ISSUE TITLE
Merge dao branch to Tribler:dao

### ISSUE THREAD

**Issue by PraveshMoelchand** [emieldesmidt/trustchain-superapp#24]
We have to merge our current `dao` branch to the [`Tribler:dao`](https://github.com/tribler/trustchain-superapp/tree/dao) branch. This will however cause some problems as new changes have been pushed to the [`kotlin-ipv8`](https://github.com/tribler/kotlin-ipv8) repo. See the comments below for further explanation

**Comment by PraveshMoelchand** [comment]
When I [updated the `kotlin-ipv8` submodule](https://github.com/emieldesmidt/trustchain-superapp/pull/18/commits/8c444f8e324de14ddf6b76a7b5a7b6bbe7143a2e) in our repo, the CI started failing due to our tests failing with the following [error](https://github.com/emieldesmidt/trustchain-superapp/runs/610350577):
```
Task :common:generateReleaseUnitTestStubRFile
e: /Users/runner/runners/2.169.0/work/trustchain-superapp/trustchain-superapp/common/src/test/java/nl/tudelft/trustchain/common/util/VotingHelperTest.kt: (53, 19): Unresolved reference: cryptoProvider
``` 

So I thought, let's just fix the unresolved reference by [simply removing it](https://github.com/emieldesmidt/trustchain-superapp/pull/18/commits/dc19fcf200296041cb829440c109d18c04ca7131). This resolved the errors from `VotingHelperTest.kt`, but then the following went [wrong](https://github.com/emieldesmidt/trustchain-superapp/runs/610368733)
```
> Task :ipv8:compileTestKotlin FAILED
e: /Users/runner/runners/2.169.0/work/trustchain-superapp/trustchain-superapp/kotlin-ipv8/ipv8/src/test/java/nl/tudelft/ipv8/BaseCommunityTest.kt: (21, 2): Unresolved reference: OptIn
e: /Users/runner/runners/2.169.0/work/trustchain-superapp/trustchain-superapp/kotlin-ipv8/ipv8/src/test/java/nl/tudelft/ipv8/BaseCommunityTest.kt: (21, 8): This class can only be used as an annotation or as an argument to @UseExperimental
e: /Users/runner/runners/2.169.0/work/trustchain-superapp/trustchain-superapp/kotlin-ipv8/ipv8/src/test/java/nl/tudelft/ipv8/attestation/trustchain/TrustChainCrawlerTest.kt: (19, 2): Unresolved reference: OptIn
e: /Users/runner/runners/2.169.0/work/trustchain-superapp/trustchain-superapp/kotlin-ipv8/ipv8/src/test/java/nl/tudelft/ipv8/attestation/trustchain/TrustChainCrawlerTest.kt: (19, 8): This class can only be used as an annotation or as an argument to @UseExperimental
```

The change that is causing all these errors is most likely introduced [here](https://github.com/Tribler/kotlin-ipv8/commit/f35c803ade8d991602a90a745e4c701fe9e38a92) when Matt removed cryptoProvider` from the community and started using `defaultCryptoProvider`

I hope this gives you enough pointers to be able to fix the issue, otherwise, let me know

**Comment by emieldesmidt** [comment]
Thanks for the hints. I've succesfully merged the tribler dao branch into our project ( see the dao-rebase branch). This did not bring any issues as you mentioned. Is there something I'm missing regarding the ipv8 module?

**Comment by emieldesmidt** [comment]
Update, upon updating the ipv8 module specifically, the errors you mentioned did appear. Strange thing is that [simply removing it](https://github.com/emieldesmidt/trustchain-superapp/pull/18/commits/dc19fcf200296041cb829440c109d18c04ca7131) did not induce further issues for me.
