### ISSUE TITLE
Update README.md in voting-module (deliverable)

### ISSUE THREAD

**Issue by PraveshMoelchand** [emieldesmidt/trustchain-superapp#28]
The README of the voting-module should be updated to clearly showcast the capabilities of the module and reflect the state of the deliverable. Also see the following examples https://github.com/Tribler/trustchain-superapp/blob/dao/trustchain-trader/readme.md & https://github.com/Tribler/trustchain-superapp/blob/dao/trustchain-payloadgenerator/readme.md

The content that is in here should be linked from the content of #27

**Comment by emieldesmidt** [comment]
Adding them here as backup
![proposal_list](https://user-images.githubusercontent.com/17474698/80521306-1b516500-898b-11ea-9f02-f982db4c3cde.gif)
